### ISSUE TITLE
Sobre o programa

### ISSUE THREAD

**Issue by lvasantos** [laisbastosbg/taskinator#3]
# Oi oi, Lais !

Não entendi bem o motivo de ser utilizado o atomically. Pode me explicar ?

https://github.com/laisbastosbg/taskinator/blob/331e2004c9f4c32a38eb572479af653fdb01f75d/Sources/taskinator/File.swift#L58

**Comment by laisbastosbg** [comment]
De acordo com a documentação:

### Declaração
```swift
func write(toFile path: String, atomically useAuxiliaryFile: Bool, encoding enc: UInt) throws
```
### Parâmetros
`useAuxiliaryFile
If true, the receiver is written to an auxiliary file, and then the auxiliary file is renamed to path. If false, the receiver is written directly to path. The true option guarantees that path, if it exists at all, won’t be corrupted even if the system should crash during writing.`

Basicamente, se o atomically for true o texto será escrito em um arquivo temporário antes de ser movido pro caminho especificado e garante que o arquivo não será corompido mesmo se o sistema travar, se for false, será escrito direto no caminho.
