### ISSUE TITLE
Uma simples sugestão

### ISSUE THREAD

**Issue by Thaynara-Andrade** [laisbastosbg/taskinator#5]
Muito bem elaborado!

Porém tenho uma sugestão, senti falta de comentários no código. Por o código ser um pouco extenso seria interessante ter comentários em linhas especificas informando o que esta sendo executado naquele bloco de instruções.

Parabéns pelo projeto, um abraço <3

**Comment by laisbastosbg** [comment]
Oi, Thaynara, eu escrevi o programa tentando pôr em prática princípios de [código limpo](https://blog.geekhunter.com.br/praticar-codigo-limpo/), como dar nomes significativos às funções e variáveis, para evitar a necessidade de comentários. Se existem alguma parte do código que você está tendo dificuldade para entender, você pode abrir uma issue separada, assim eu posso melhorar a qualidade do código ^^
